services:
  web:
    build: .
    command: "./bin/rails server"
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "sqlite3:///rails/storage/production.sqlite3"
      REDIS_URL: "redis://redis:6379/1"
    volumes:
      - rails_storage:/rails/storage
    depends_on:
      - redis

  worker:
    build: .
    command: "./bin/bundle exec sidekiq"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "sqlite3:///rails/storage/production.sqlite3"
      REDIS_URL: "redis://redis:6379/1"
    volumes:
      - rails_storage:/rails/storage
    depends_on:
      - redis

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  rails_storage:
  redis_data:
